### ISSUE TITLE
How to compile PSXTransfer on Windows?

### ISSUE THREAD

**Issue by abewartech** [rasoulia/PSXTransfer#1]
Hi @rasoulia,

I'm trying to compile PSXTransfer on Windows, but I'm encountering some difficulties. I followed the instructions provided in the repository's README file, but I'm still facing issues.

Could you please provide some guidance on how to compile PSXTransfer on Windows? Specifically, I would like to know the necessary steps, dependencies, and any additional instructions that might be required for the Windows environment.

Any help or insights you can provide would be greatly appreciated.

Thank you!

**Comment by rasoulia** [comment]
Hi. Can you show me the errors? I use vs 2022 with net 6
But at first rebuild solution to download all dependencies.

**Comment by abewartech** [comment]
`D:\experimentv4\PSXTransfer\PSXTransfer\PSXTransfer.csproj : error  : The SDK resolver type "DotNetMSBuildSdkResolver" failed to load. The type initializer for 'Microsoft.DotNet.DotNetSdkResolver.VSSettings' threw an exception.  D:\experimentv4\PSXTransfer\PSXTransfer\PSXTransfer.csproj

D:\experimentv4\PSXTransfer\PSXTransfer.DLL\PSXTransfer.DLL.csproj : error  : The SDK resolver type "DotNetMSBuildSdkResolver" failed to load. The type initializer for 'Microsoft.DotNet.DotNetSdkResolver.VSSettings' threw an exception.  D:\experimentv4\PSXTransfer\PSXTransfer\PSXTransfer.csproj

`

**Comment by rasoulia** [comment]
This problem is not related to source it's related to your ide and compiler. Just use latest version of vs code or vs2022 must solve the problem


https://github.com/dotnet/msbuild/issues/4227

https://stackoverflow.com/questions/53435365/visual-studio-2017-the-sdk-resolver-type-dotnetmsbuildsdkresolver-failed-to-l
