### ISSUE TITLE
برنامه جدید

### ISSUE THREAD

**Issue by IRONB0SS** [rasoulia/PSXTransfer#3]
سلام آقای رسولی، وقت بخیر
خوب هستید
یه سوال داشتم امکانش هست برنامه رو من یه هفته امتحان کنم و دیدم خوشم اومد، ماهی ۱تومن پرداخت کنم تا ۵تومن کامل بشه؟
من بالاخره از شنبه مغازه رو باز میکنم و می‌خوام بهترین برنامه دیتا رو داشته باشم :))

**Comment by rasoulia** [comment]
سلام وقت شما هم بخیر.
مبارکتون باشه.
شرمنده بنا به دلایلی کلا از فروش نسخه جدید منصرف شدم. از نسخه قدیمی استفاده کنید با تشکر از شما

**Comment by IRONB0SS** [comment]
قصد انتشار بصورت رایگان هم ندارید؟ واقعا حیفه برنامه‌ای حرفه‌ای رو منتشر نکنید
احیانا نظرتون عوض شد، آیدی تلگرام میذارم
@msafari

قول مردانه میدم که برنامه رو هم بدون اجازه شما منتشر نکنم، برنامه فعلی مشکل دیتابیس داره، فایل به دیتابیس بعضاً اضافه نمیشه

با تشکر از زحمات شما

**Comment by rasoulia** [comment]
عذرخواهی میکنم ولی فعلاً امکان انتشار چه پولی و چه رایگان رو ندارم.
اگه سورس نسخه قدیمی روی سیستمم باشه این مشکل رو نگاه میکنم و برطرف میکنم.
